### ISSUE TITLE
Unknown Function/const RegexDigit error

### ISSUE THREAD

**Issue by aalhuz** [z3str/Z3-str#10]
I've tried to run the solver on one of the testcases regex-044 but I got this error 
Unknown Function/const RegexDigit

Thanks

**Comment by z3str** [comment]
Thanks! The test cases were not updated correctly and I just synced them. The previous one was for an older version. Actually, the operator `"RegexDigit"` has been removed, as it seems to be clearer to use `(RegexStar (RegexCharRange "0" "9") )`.

Thanks,
-Yunhui
