### ISSUE TITLE
Unsound result

### ISSUE THREAD

**Issue by SaswatPadhi** [z3str/Z3-str#2]
On the latest version, the following input:

```
(declare-const r String)
(declare-const s String)

(assert (= s "aa"))
(assert (= r (Concat (Replace s "aa" "x") "a")))

(assert (not (= (Length s) (Length r))))

(check-sat)
```

produces:

```
>> SAT
------------------------
s : string -> "aa"
r : string -> "aaa"
```

**Comment by z3str** [comment]
Hi Saswat,

Thanks for the feedback! This is a bug and it has been fixed. I just checked in the changes. Could you sync and try again?

Thanks,
-Yunhui

**Comment by SaswatPadhi** [comment]
Awesome. It works as expected now.

Thanks Yunhui.
