### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by nolleryc** [z3str/Z3-str#9]
Hi all,

is there a possibility to have an python API for your z3-str?

Cheers,
Yannic

**Comment by z3str** [comment]
Hi,

We don't have a python API yet. But yes, it's possible. We know [an older version has been extended to support python APIs](http://g.csail.mit.edu/gitweb/?p=z3str.git;a=blob;f=z3str/z3str.py;h=424648ae4174bd6aabac95951326ca54c602ed44;hb=refs/heads/master)

Thanks,
-Yunhui

**Comment by nolleryc** [comment]
Thanks, I was not able to get this running on my Windows 7 machine, but on my Ubuntu 14.04 machine.

**Comment by nolleryc** [comment]
Thanks, I was not able to get this running on my Windows 7 machine, but on my Ubuntu 14.04 machine.
